### ISSUE TITLE
Log viewer

### ISSUE THREAD

**Issue by evilpilaf** [serilog/serilog-sinks-azuretablestorage#11]
Is there a way to view, query and manage the logs stored in table storage similar to Seq or the likes?

**Comment by nblumhardt** [comment]
Howdy - not any I'm aware of, but please update us if you find one. Cheers!

**Comment by CassandraDied** [comment]
Visual Studio is capable of viewing, querying and editing data from Cloud Explorer window.

**Comment by robdmoore** [comment]
Check this thread out: https://twitter.com/robdmoore/status/747938007987085317
