### ISSUE TITLE
SeriLog Azure Table Storage Asp .Net Core

### ISSUE THREAD

**Issue by AnandPrakash05** [serilog/serilog-sinks-azuretablestorage#16]
Hi Team,
I am trying to implement SeriLog Logging framework to log the details in Azure Table Storage in Asp .Net Core but it seems .Net Core doesn't supports any version of the "Serilog.Sinks.AzureTableStorage" dependency. I have read few blogs and its mentioned that team is working on to get the support for Asp .Net Core for Azure Table Storage.

Could you please let me know when you can expect the support for the same ?

Thank You!!

**Comment by melenaos** [comment]
Hi,
I need this sink too for my MVC Core project. Is there any plan migrating it to NetStandard? 
I would like to help if you need testing or even developing on this project.

**Comment by nblumhardt** [comment]
The latest version supports .NET Core through .NET Standard 1.3 - https://www.nuget.org/packages/serilog.sinks.azuretablestorage

Cheers!

**Comment by melenaos** [comment]
Super! I tested the day before publishing and I was sad to leave serilog but both needed sinks, this and Mail have been released in these two days! 
Congratulation for this excellent library!
