### ISSUE TITLE
New line issue in rowkey

### ISSUE THREAD

**Issue by pandazzurro** [serilog/serilog-sinks-azuretablestorage#23]
I found an error when sink generate rowkey including newline and/or carriage return.
[This is my fix](https://github.com/pandazzurro/serilog-sinks-azuretablestorage/commit/04b2f6aeeb4fe5123978e9058d23118e7e870341)

**Comment by nblumhardt** [comment]
Thanks, makes sense. Are you keen to PR the change?

**Comment by nblumhardt** [comment]
#24
