### ISSUE TITLE
Output template for column creation from parameters?

### ISSUE THREAD

**Issue by sturlath** [serilog/serilog-sinks-azuretablestorage#26]
#### Control column creation
What I would really like is ** a way to select what properties become a column** in the azure table when using **AzureTableStorageWithProperties**().

Something like e.g RollingFile is using
_{Timestamp:dd-MM-yyyy HH:mm:ss.fff zzz} {Level} {MachineName} {ThreadId} {ProcessId}{MemberName}{Message}{Exception}_ where each {} would become a column and just them, others would be skipped.

But I would **also** like to have the option to **_keep the json Data column_** that **AzureTableStorage**() creates. I don´t want to loose that.

**Has anything like this been discussed?** What are the problems? I will also dig around the code in the meantime.

**Comment by adamchester** [comment]
👍 From me. I haven't seen this discussed before. Maybe @nblumhardt would know if something similar has been done is any other sinks?

**Comment by adamchester** [comment]
I do wonder if would be appropriate to use message template syntax to declare which properties become columns. Wouldn't it be easier to just provide a list (maybe csv would fit with configuration options)?

**Comment by nblumhardt** [comment]
I think the most similar functionality right now would be in the SQL Server sink - https://github.com/serilog/serilog-sinks-mssqlserver.

In that case, an "options" class is used. It's not particularly configuration-friendly, so there's room to improve the way we approach it (or the configuration API).

**Comment by montijr2007** [comment]
I also would really like to be able to specify the additional columns to be added to the Azure Storage. Auto-creating columns for ALL of the data properties is way overboard. Some ideas:
1.) Add only Enriched properties to the Azure data tables
2.) Specify a column configuration class like @nblumhardt  mentioned (how mssqlserver sink does it)

In the meantime, anyone know how to configure only a few additional columns without it auto-creating  a column for everything?

**Comment by nblumhardt** [comment]
Just to link things up: #31 is a PR from @montijr2007 for this.

I'm not using table storage so it's hard for me to reach a solid conclusion on what the correct behaviour/trade-offs are. Might be good to continue the discussion over on the PR.

**Comment by untilted-document** [comment]
Any chance we could extend this so that any column the logger wants to write is checked against this array first? I'd like to e.g. pass an array of `new string[] { "Level", "RenderedMessage", "Exception" }` to have those columns, but knock out the MessageTemplate and AggregatedProperties columns, that I do not care to log

**Comment by nblumhardt** [comment]
Just a note, the PR for this one has been merged, would be better to open a new ticket for follow-on work. Cheers!
