### ISSUE TITLE
Issue using AzureTableStorage and ASP.NET Core 1.0

### ISSUE THREAD

**Issue by MrKevHunter** [serilog/serilog-sinks-azuretablestorage#3]
Hi,

When I try to use ASP.NET Core 1.0 and Serilog to log to table storage I get the following message

Could not load file or assembly 'Serilog.FullNetFx, Version=1.4.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10' or one of its dependencies. The system cannot find the file specified."

my project.json looks like this

    "Serilog": "2.0.0-beta-456",
    "Serilog.Framework.Logging": "1.0.0-rc1-final-10083",
    "Serilog.Sinks.AzureTableStorage": "1.5.11"

and it crashes on this line

            Log.Logger = new LoggerConfiguration()
                .WriteTo.Trace()
                .WriteTo.AzureTableStorage(storage)
                .CreateLogger();

Have I misconfigured something or is it not compatible with RC1 yet?

Thanks

**Comment by nblumhardt** [comment]
Hi - I'd guess the AzureTableStorage sink isn't compatible with Core yet; currently working on a backlog of Core work, may be a little while. For now, embedding the sink code directly in your project is probably the quickest way to get unblocked. HTH!

**Comment by MrKevHunter** [comment]
Thanks, We're probably just going to buy Seq instead ;-)

**Comment by nblumhardt** [comment]
@MrKevHunter perfect :-) .. All the best!

**Comment by Huck** [comment]
Hi, we are having the same issue on:
```

configs.Add(new KeyValuePair<string, string>("using:_CommandLineSettingsSerilogFullNetFx", "Serilog.FullNetFx"));

            Log.Logger = new LoggerConfiguration()
                .ReadFrom.KeyValuePairs(configs)
                .CreateLogger();
```
we are using ASP.NET 5, but not Core (dnx46). shouldn't this just work?

`"Serilog.Extensions.Logging": "1.0.0-rc1-final-10092",
    "Serilog": "2.0.0-beta-465"`

thanks

**Comment by nblumhardt** [comment]
@Huck very few sinks apart from the basics (Console, RollingFile/File, Seq) have been ported to work with Serilog 2, which has breaking changes intended to fit the new platform better.

In your scenario (dnx46) you should be able to use Serilog 1.5 and the other sinks to get the behaviour you need. Serilog 2.0 beta is only required if you want more .NET Core compatibility.

Hope this helps, let me know if you hit any issues.

**Comment by Huck** [comment]
good to know, thanks
