### ISSUE TITLE
Allow using an SAS uri for logging purposes

### ISSUE THREAD

**Issue by liamdawson** [serilog/serilog-sinks-azuretablestorage#36]
I'd love to be able to restrict it so that the application only has access to a write-only SAS uri for logging purposes (so it can't tamper with or read the logs), but it appears (AFAICT) that neither `connectionString` nor the `CloudStorageAccount` support SAS uris.

**Comment by cdavid** [comment]
As per https://twitter.com/nblumhardt/status/937450195125616640 , @nblumhardt :)

I would like to fix this. In the process, I would move to CSPROJ and probably update the dependencies:
* WindowsAzure.Storage to 8.6.0. I am confused on why there are 2 targets frameworks (netstandard and .NET 4.5) with two differnet Azure Storage version references. As per here: https://github.com/Azure/azure-storage-net/blob/master/README.md - .NET 4.5 is natively supported (though after December 2016, so maybe there is some history here I don't know?).
* Serilog 2.5.0 - are there any things coming in 2.6 that is worth waiting for?
* Serilog.Sinks.PeriodicBatching 2.1.1 - right now on 2.1.0.

Anything else I should keep an eye out for - I am still learning about Serilog, sinks etc.?

**Comment by nblumhardt** [comment]
Thanks for the follow-up @cdavid 👍 

> move to CSPROJ and probably update the dependencies

See https://github.com/serilog/serilog-sinks-console for standard _Build.ps1_ and _appveyor.yml_ files that can be dropped into this repo once the CSPROJ has been converted.

> WindowsAzure.Storage to 8.6.0. I am confused on why there are 2 targets frameworks (netstandard and .NET 4.5) with two differnet Azure Storage version references. As per here: https://github.com/Azure/azure-storage-net/blob/master/README.md - .NET 4.5 is natively supported (though after December 2016, so maybe there is some history here I don't know?).

I think this is historical. How about we bump the major version of this package, and move all supported targets to the same, latest storage package?

> Serilog 2.5.0 - are there any things coming in 2.6 that is worth waiting for?

Not for this lib - 2.5 is fine.

> Serilog.Sinks.PeriodicBatching 2.1.1 - right now on 2.1.0.

Sounds good.

> Anything else I should keep an eye out for - I am still learning about Serilog, sinks etc.?

https://gitter.im/serilog/serilog is fairly active, in case you need any help through the process.

Thanks!
