### ISSUE TITLE
Filtering for azure table storage

### ISSUE THREAD

**Issue by mattwoberts** [serilog/serilog-sinks-azuretablestorage#38]
Hi,

Is is possible, or could it be possible, to filter logs JUST for the azure table storage.

Say for example I want all logs to go to the console, but for azure, I only want events from my app, not Microsoft ones, to go to the azure table storage - is that possible?

Here's my current config:

           var logger = new LoggerConfiguration()
                .WriteTo.Console()
                .MinimumLevel.Information()
                .MinimumLevel.Override("MyApp",LogEventLevel.Debug)
                .WriteTo.AzureTableStorage(CloudStorageAccount.Parse(Configuration.GetConnectionString("Logging")),
                    storageTableName:"TEstLogs",
                    keyGenerator: new SerilogAzureTableStorageRowKey())
                .CreateLogger();

Thanks

**Comment by nblumhardt** [comment]
Hi @mattwoberts -

I think you'll need a sub-pipeline with the filter on it; something like:

```csharp
 var logger = new LoggerConfiguration()
    .WriteTo.Console()
    .MinimumLevel.Information()
    .MinimumLevel.Override("MyApp",LogEventLevel.Debug)
    .WriteTo.Logger(lc => lc
        .Filter.ByExcluding(Matching.FromSource("Microsoft"))
        .WriteTo.AzureTableStorage(CloudStorageAccount.Parse(Configuration.GetConnectionString("Logging")),
            storageTableName:"TEstLogs",
            keyGenerator: new SerilogAzureTableStorageRowKey()))
    .CreateLogger();
```

**Comment by mattwoberts** [comment]
Ah cool, that get's me nearer to what i want.

Thanks!

**Comment by mahdighorbanpour** [comment]
I want to achieve the same goal but via configurations in the appSettings.json. however, when I try to filter only for AzureTableStorage, it doesn't work anymore!
here is my working config without filtering:
`"Serilog": {
    "WriteTo": [
      {
        "Name": "Console"
      },
      {
        "Name": "AzureTableStorageWithProperties",
        "Args": {
          "storageTableName": "PortalLogs",
          "connectionString": "xxxx",
          "propertyColumns": [ "Scope", "RequestId" ]
        },
        "outputTemplate": "{Timestamp:o} [{Level:u3}] ({Application}/{MachineName}/{ThreadId}) {Properties:j} {Scope} {Message}{NewLine}{Exception}"
      }
    ],
    "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ]
  }`

and here is my config to enable filtering only for Azure. I copied it from examples page and just changed it a little bit, even thought I have not included any filtering, it doesn't work at all, I get no logs on Azure anymore:
`"Serilog": {
    "WriteTo:Sublogger": {
      "Name": "Logger",
      "Args": {
        "configureLogger": {
          "MinimumLevel": "Verbose",
          "WriteTo": [
            {
              "Name": "Console",
              "Args": {
                "outputTemplate": "[{Timestamp:HH:mm:ss} {SourceContext} [{Level}] {Message}{NewLine}{Exception}",
                "theme": "Serilog.Sinks.SystemConsole.Themes.SystemConsoleTheme::Grayscale, Serilog.Sinks.Console"
              }
            }
          ]
        },
        "restrictedToMinimumLevel": "Verbose"
      }
    },
    "WriteTo:AzureTableStorageWithProperties": {
      "Name": "AzureTableStorageWithProperties",
      "Args": {
        "configure": [
          {
            "Name": "AzureTableStorageWithProperties",
            "Args": {
              "storageTableName": "PortalLogs",
              "connectionString": "xxxxxx",
              "propertyColumns": [ "Scope", "RequestId" ]
            },
        "outputTemplate": "{Timestamp:o} [{Level:u3}] ({Application}/{MachineName}/{ThreadId}) {Properties:j} {Scope} {Message}{NewLine}{Exception}"
      
          }
        ]
      }
    },
    "WriteTo:ConditionalSink": {
      "Name": "Conditional",
      "Args": {
        "expression": "@Level in ['Error', 'Fatal']",
        "configureSink": [
          {
            "Name": "File",
            "Args": {
              "path": "%TEMP%/Logs/serilog-configuration-sample-errors.txt"
            }
          }
        ]
      }
    },
    "Enrich": [
      "FromLogContext",
      "WithThreadId"
    ],
    "Properties": {
      "Application": "MyPortal"
    }
  }`
