### ISSUE TITLE
Works on first use, then 409 conflict 

### ISSUE THREAD

**Issue by stokara** [serilog/serilog-sinks-azuretablestorage#53]
If I delete the table it works again one time.   I tried
 Serilog.Debugging.SelfLog.Enable(x => Debug.WriteLine(x)); 
but nothing is output.

On the first Log statement I get this in the Debug window if Visual Studio:
Exception thrown: 'System.Net.WebException' in System.dll
The remote server returned an error: (409) Conflict.
 Using Fiddler I see I am getting: TableAlreadyExists returned 

In a standalone console app it works fine.  The problem occurs only my WPF app.
In the offending WPF app, I created my own ICloudTableProvider and used a synchronous call for table.Exists and table.Create and it now works.  Could there be a problem with SyncContextSafeWait.  when using WPF  [STAThread]?

**Comment by kashifsoofi** [comment]
It seems something to do with WPF as the solution is working fine for me in a webapi solution (azure webapp). Unfortunately I don't have access to a windows machine to tryout a WPF application, will have to wait until I get some free time at work.

**Comment by stokara** [comment]
By using bypassTableCreationValidation:true I able to bypass the first chance exception that are thrown and it works.

As a general rule sync over async causes subtle issues.  It seems that the .net standard lib only has async methods which caused this sync over async workaround. 
As it is making a web call anyway it would make sense if ICloudTableProvider was changed to have an async GetCloudTable method (GetCloudTableAsync) instead of the sync GetCloudTable.
However, I see that this is necessitated because ILogEventSink.Emit is synchronous.  I imagine the codebase would be improved with "async all the way" but I imagine this would be lot of work to achieve

**Comment by adamchester** [comment]
Thanks for stopping by @stokara, and thanks for posting here so we can all benefit.

You might find this thread helps with reasoning why the logging pipeline is not async: 

https://github.com/serilog/serilog/issues/134
