### ISSUE TITLE
Table Format

### ISSUE THREAD

**Issue by bjorncoltof** [serilog/serilog-sinks-azuretablestorage#7]
I've been reviewing this sink for usage in our applications. One big issue we have identified is that the chosen scheme for the rowkey messes up the order in table storage when lots happens at the 'same' time (also when using batching). I have made the modifications to the sink by adjusting the code in this repository, would you be interested in PR for this or should I keep this a separate sink (since the table format changes) and package it myself?

**Comment by nblumhardt** [comment]
Hi @bjorncoltof - it sounds like it'd be a possible inclusion here, but others are more familiar with the format than I am. If you can post a PR it's definitely got a good chance!

Thanks for the heads-up, either way :+1:

**Comment by adamchester** [comment]
:+1: to this - it is annoying

**Comment by bjorncoltof** [comment]
This issue has been solved by #9 for us.
