### ISSUE TITLE
Please fix build

### ISSUE THREAD

**Issue by djsowa** [serilog/serilog-sinks-azuretablestorage#76]
Please fix Your build so recent changes are published on Nuget:
https://ci.appveyor.com/project/serilog/serilog-sinks-azuretablestorage/branch/master

**Comment by nblumhardt** [comment]
5.0 build just succeeded; seems like there may be some issues with triggering AppVeyor for the dev branch build, but will have to leave that for now.

https://ci.appveyor.com/project/serilog/serilog-sinks-azuretablestorage
